### ISSUE TITLE
`transact` on mocked connection throws, instead of on the deref

### ISSUE THREAD

**Issue by awkay** [vvvvalvalval/datomock#7]
I've noticed a subtle difference with datomock connections over the Datomic ones. When you transact on Datomic, any problem isn't thrown until you deref the result. When mocking the connection the exception happens on transact instead of the deref.

**Comment by vvvvalvalval** [comment]
That's right, fixing right now, thanks!

**Comment by vvvvalvalval** [comment]
@awkay Fixed in https://github.com/vvvvalvalval/datomock/releases/tag/v0.2.1.
